# install ruby using rbenv
- name: register rbenv installed
  sudo: no
  stat:
    path: "~/.rbenv/.git"
  register: rbenv_installed
  tags:
    - install-ruby

- name: create ~/.rbenv directory
  sudo: no
  file:
    path: "~/.rbenv"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0755
    state: directory
  tags:
    - install-ruby
    - create-dir

#@todo dependencies ?
- name: install git
  sudo: yes
  yum:
    name: git
    state: present
  tags:
    - install-ruby
    - install-git
 
- name: install rbenv
  sudo: no
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv/
  when: rbenv_installed.stat.exists == false
  tags:
    - install-ruby
    - install-git

- name: configure rbenv env into bash_profile
  sudo: no
  lineinfile:
    line: "{{ item }}"
    state: present
    dest: ~/.bash_profile
  with_items:
    - 'export PATH="$HOME/.rbenv/bin:$PATH"'
    - 'export PATH="$HOME/.rbenv/shims:$PATH"'
    - 'eval "$(rbenv init -)"'
  tags:
    - install-ruby
    - configure-rbenv-env

- name: install ruby-build
  sudo: no
  git: 
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build/
  when: rbenv_installed.stat.exists == false
  tags:
    - install-ruby
    - install-ruby-build

# bash に l オプションでログインシェルとして起動して実行する。
# .bash_profileの環境変数を読み込むため。
# bash with l option because of reading export PATH at .bash_profile.
# @see http://www.bunkei-programmer.net/entry/2015/05/16/162020
- name: Install ruby with ruby_version
  sudo: no
  shell: /bin/bash -lc "rbenv install {{ ruby_version }} && rbenv rehash && rbenv global {{ ruby_version }}"
  when: rbenv_installed.stat.exists == false
  tags:
    - install-ruby

- name: install ruby development tools
  sudo: yes
  yum:
    name: "{{ item }}" 
    state: present
  with_items:
    - ruby-devel
    - rubygems
  tags:
    - install-ruby

- name: install bundler
  gem:
    name: bundler
    executable: ~/.rbenv/shims/gem
    user_install: no
  when: rbenv_installed.stat.exists == false
  tags:
    - install-ruby


